name: Run Regression Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: 'pip'
        cache-dependency-path: utils/scripts/requirements.txt
    - run: pip install -r utils/scripts/requirements.txt
    - name: run tests
      run: python ./tests/run_test.py -q -c "./" "A_000001"